---
- hosts: nodes
  become: yes
  tasks:
    - name: Creating a file
      file:
        dest: "/home/ec2-user/premji.txt"
        state: touch
    - name: Creating a directory
      file:
        dest: "/home/ec2-user/premji"
        state: directory
