---
- hosts: nodes
  become: yes
  gather_facts: False
  tasks:
  - name: Creating multiple files wit different permissions
    file:
      path: "{{ item.location }}"
      state: touch
      mode: "{{ item.mode }}"
    with_items:
    - { location: '/tmp/filer123',mode: '0566' }
    - { location: '/tmp/filer456',mode: '0755' }

